-- 코드를 입력하세요
SELECT A.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(PRICE*SALES) AS 'TOTAL_SALES'
FROM BOOK BI 
    JOIN AUTHOR A ON BI.AUTHOR_ID = A.AUTHOR_ID
    JOIN (
        SELECT BOOK_ID, SALES
        FROM BOOK_SALES
        WHERE SALES_DATE LIKE '2022-01%'
    ) AS BS
    ON BI.BOOK_ID = BS.BOOK_ID
GROUP BY A.AUTHOR_ID, CATEGORY
ORDER BY A.AUTHOR_ID, CATEGORY DESC


# SELECT *
# FROM BOOK_SALES
# WHERE SALES_DATE LIKE '2022-01%'
# ORDER BY BOOK_ID, sales_date

# SELECT *
# FROM BOOK