-- 코드를 입력하세요
SELECT MONTH(START_DATE) AS "MONTH", CAR_ID, COUNT(MONTH(START_DATE)) AS "RECORDS"
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE DATE_FORMAT(START_DATE, "%y-%m") IN ("22-08", "22-09", "22-10")
    AND CAR_ID IN (
        SELECT CAR_ID 
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
        WHERE DATE_FORMAT(START_DATE, "%y-%m") IN ("22-08", "22-09", "22-10")
        GROUP BY CAR_ID 
        HAVING COUNT(CAR_ID) > 4)
GROUP BY MONTH(START_DATE), CAR_ID
HAVING COUNT(CAR_ID) != 0 
ORDER BY MONTH(START_DATE), CAR_ID DESC

# SELECT MONTH(START_DATE), CAR_ID 
#         FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
#         WHERE  DATE_FORMAT(START_DATE, "%y-%m") IN ("22-08", "22-09", "22-10")
#         GROUP BY CAR_ID 
#         HAVING COUNT(CAR_ID) > 4
        
# SELECT DATE_FORMAT(START_DATE, "%y-%m")
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE DATE_FORMAT(START_DATE, "%y-%m") IN ("22-08", "22-09", "22-10")

# SELECT MONTH(START_DATE) AS "MONTH", CAR_ID, COUNT(MONTH(START_DATE)) AS "RECORDS"
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE (SELECT CAR_ID, CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY GROUP BY CAR_ID HAVING COUNT(CAR_ID)) > 4
# GROUP BY MONTH(START_DATE), CAR_ID
# HAVING 

#"22-08" OR "22-09" OR "22-10" = DATE_FORMAT(START_DATE, "%y-%m")


# SELECT COUNT(CAR_ID), CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY GROUP BY CAR_ID HAVING COUNT(CAR_ID) > 4
# SELECT *
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE "22-08" OR "22-09" OR "22-10" = DATE_FORMAT(START_DATE, "%y-%m")
# ORDER BY CAR_ID
# GROUP BY CAR_ID


# SELECT DATE_FORMAT(START_DATE, "%y-%m")
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE CAR_ID = 15
