-- 코드를 입력하세요
# 중복되는 CAR_ID들 중에서 11월 달에 렌탈되는 모든 CAR는 사용 못함. 
# 즉 날짜를 구할 때 하나라도 포함되는 것이 있는 ID를 불러와서 NOT IN으로 처리 해야함.

SELECT A.CAR_ID, A.CAR_TYPE, ROUND(A.DAILY_FEE*30 * ((100-DISCOUNT_RATE)/100), 0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR A JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C
ON  C.CAR_TYPE = A.CAR_TYPE AND DURATION_TYPE = '30일 이상'
WHERE A.CAR_ID NOT IN (
        SELECT B.CAR_ID 
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY B
        WHERE END_DATE >= '2022-11-01' AND START_DATE <= '2022-11-01'
    )
AND A.CAR_TYPE IN ('SUV', '세단')
AND A.DAILY_FEE*30 * ((100-DISCOUNT_RATE)/100) BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC