-- 코드를 입력하세요
SELECT F.FLAVOR
FROM FIRST_HALF F JOIN (
    SELECT (F.TOTAL_ORDER + J.JTO) AS TOTAL, J.FLAVOR
    FROM FIRST_HALF F JOIN (
        SELECT SUM(TOTAL_ORDER) AS JTO, FLAVOR
        FROM JULY
        GROUP BY FLAVOR
        ) J
        ON F.FLAVOR = J.FLAVOR
    ORDER BY (F.TOTAL_ORDER + J.JTO) DESC LIMIT 3
    ) J2
WHERE F.FLAVOR = J2.FLAVOR
ORDER BY J2.TOTAL DESC


