-- 코드를 입력하세요
# SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, 
#     COUNT(A.USER_ID) AS PUCHASED_USERS, 
#     ROUND(COUNT(MONTH(SALES_DATE))/(
#         SELECT COUNT(*)
#         FROM USER_INFO
#     ), 1) AS PUCHASED_RATIO
# FROM ONLINE_SALE A JOIN (
#     SELECT USER_ID
#     FROM USER_INFO 
#     WHERE JOINED BETWEEN '2021-01-01' AND '2021-12-31'
# ) B
# ON A.USER_ID = B.USER_ID
# GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
# ORDER BY YEAR, MONTH


# SELECT *
# FROM ONLINE_SALE A JOIN (
#     SELECT USER_ID
#     FROM USER_INFO 
#     WHERE JOINED BETWEEN '2021-01-01' AND '2021-12-31'
#     GROUP BY USER_ID
# ) B
# ON A.USER_ID = B.USER_ID
# # GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
# ORDER BY SALES_DATE


# SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, 
#     COUNT(A.USER_ID) AS PUCHASED_USERS, 
#     ROUND(COUNT(MONTH(SALES_DATE))/(
#         SELECT COUNT(*)
#         FROM USER_INFO
#     ), 1) AS PUCHASED_RATIO
# FROM ONLINE_SALE A JOIN (
#     SELECT USER_ID
#     FROM USER_INFO 
#     WHERE JOINED BETWEEN '2021-01-01' AND '2021-12-31'
# ) B
# ON A.USER_ID = B.USER_ID
# GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
# ORDER BY YEAR, MONTH


SELECT YEAR, MONTH, COUNT(A.USER_ID) AS PUCHASED_USERS,
    ROUND(COUNT(MONTH)/(
        SELECT COUNT(*)
        FROM USER_INFO
        WHERE JOINED BETWEEN '2021-01-01' AND '2021-12-31'
    ), 1) AS PUCHASED_RATIO
FROM USER_INFO A JOIN (
    SELECT YEAR(SALES_DATE) AS 'YEAR', MONTH(SALES_DATE) AS 'MONTH', USER_ID
    FROM ONLINE_SALE
    GROUP BY YEAR, MONTH, USER_ID
) B
ON A.USER_ID = B.USER_ID
WHERE JOINED BETWEEN '2021-01-01' AND '2021-12-31'
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH
    