-- 코드를 입력하세요
SELECT P.PRODUCT_CODE, (P.PRICE * SUM(O.SALES_AMOUNT)) AS SALES
FROM PRODUCT P JOIN OFFLINE_SALE O
WHERE P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY P.PRODUCT_ID
ORDER BY (P.PRICE * SUM(O.SALES_AMOUNT)) DESC, PRODUCT_CODE


# SELECT * FROM PRODUCT
# SELECT * FROM OFFLINE_SALE