-- 코드를 입력하세요
-- 2022년 10월 16일에 대여중인 자동차인 경우 대여 중. 반납 날짜여도 대여중.
-- 자동차 ID를 기준으로 내림 차순

SELECT C.CAR_ID,
    CASE 
    WHEN C.CAR_ID IN (SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE <= '2022-10-16' AND END_DATE >= '2022-10-16'
GROUP BY CAR_ID) 
    THEN "대여중"
    ELSE "대여 가능"
    END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C
GROUP BY CAR_ID
ORDER BY CAR_ID DESC



