-- 코드를 입력하세요
-- 2022-04-13 일에 취소 되지 않은 흉부외가 예약 내역

SELECT APNT_NO, PT_NAME, P.PT_NO, D.MCDP_CD, DR_NAME, APNT_YMD
FROM PATIENT P JOIN (
    SELECT *
    FROM APPOINTMENT
    WHERE APNT_YMD LIKE '2022-04-13%' AND NOT APNT_CNCL_YN = 'Y'
) AS A
ON P.PT_NO = A.PT_NO
JOIN DOCTOR D
ON D.DR_ID = A.MDDR_ID
WHERE A.MCDP_CD = 'CS'
ORDER BY A.APNT_YMD



# SELECT APNT_NO, PT_NAME, P.PT_NO, D.MCDP_CD, DR_NAME, APNT_YMD
# FROM PATIENT P JOIN (
#     SELECT *
#     FROM APPOINTMENT
#     WHERE APNT_YMD LIKE '2022-04-13%' AND NOT APNT_CNCL_YN = 'Y'
# ) AS A