-- 코드를 입력하세요
SELECT DISTINCT(CRCC.CAR_ID)
FROM CAR_RENTAL_COMPANY_CAR CRCC JOIN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE MONTH(START_DATE) = 10
) CI
ON CRCC.CAR_ID = CI.CAR_ID
WHERE CAR_TYPE = '세단'
ORDER BY CRCC.CAR_ID DESC