-- 코드를 입력하세요
# SELECT B.BOOK_ID, A.AUTHOR_NAME, B.PUBLISHED_DATE
# FROM BOOK B JOIN AUTHOR A
# WHERE CATEGORY = '경제'
# ORDER BY PUBLISHED_DATE

SELECT BOOK_ID, AUTHOR_NAME, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d')
FROM BOOK B JOIN AUTHOR A
WHERE CATEGORY = '경제' AND B.AUTHOR_ID = A.AUTHOR_ID
ORDER BY PUBLISHED_DATE

# SELECT * FROM BOOK
