-- 코드를 입력하세요
SELECT 
    CONCAT('/home/grep/src/',UGF.BOARD_ID,'/',FILE_ID,FILE_NAME,FILE_EXT) AS FILE_PATH
FROM 
    USED_GOODS_FILE UGF, USED_GOODS_BOARD UGB
WHERE UGB.VIEWS = (
    SELECT MAX(B.VIEWS)
    FROM USED_GOODS_BOARD AS B
) AND UGF.BOARD_ID = UGB.BOARD_ID
ORDER BY FILE_ID DESC
